// AUTO-GENERATED — do not edit by hand.
// Regenerate via: node scripts/dsa-builder/build-local-authorities.cjs

export type LocalAuthority = { name: string; address: string };

export const SCOTLAND_LOCAL_AUTHORITIES: readonly LocalAuthority[] = [
  { name: "Aberdeen City Council", address: "Marischal College, Broad Street, Aberdeen, AB10 1AB" },
  { name: "Aberdeenshire Council", address: "Woodhill House, Westburn Road, Aberdeen, AB16 5GB" },
  { name: "Angus Council", address: "Angus House, Orchardbank Business Park, Forfar, DD8 1AX" },
  { name: "Argyll and Bute Council", address: "Kilmory, Lochgilphead, PA31 8RT" },
  { name: "City of Edinburgh Council", address: "Waverley Court, 4 East Market Street, Edinburgh, EH8 8BG" },
  { name: "Clackmannanshire Council", address: "Kilncraigs, Greenside Street, Alloa, FK10 1EB" },
  { name: "Comhairle nan Eilean Siar", address: "Council Offices, Sandwick Road, Stornoway, HS1 2BW" },
  { name: "Dumfries and Galloway Council", address: "Council Offices, English Street, Dumfries, DG1 2DD" },
  { name: "Dundee City Council", address: "Dundee House, 50 North Lindsay Street, Dundee, DD1 1LS" },
  { name: "East Ayrshire Council", address: "Council Headquarters, London Road, Kilmarnock, KA3 7BU" },
  { name: "East Dunbartonshire Council", address: "12 Strathkelvin Place, Southbank Marina, Kirkintilloch, Glasgow, G66 1TJ" },
  { name: "East Lothian Council", address: "John Muir House, Brewery Park, Haddington, EH41 3HA" },
  { name: "East Renfrewshire Council", address: "Eastwood Park, Rouken Glen Road, Giffnock, Glasgow, G46 6UG" },
  { name: "Falkirk Council", address: "Municipal Buildings, West Bridge Street, Falkirk, FK1 5RS" },
  { name: "Fife Council", address: "Fife House, North Street, Glenrothes, KY7 5LT" },
  { name: "Glasgow City Council", address: "City Chambers, George Square, Glasgow, G2 1DU" },
  { name: "Inverclyde Council", address: "Municipal Buildings, Clyde Square, Greenock, PA15 1LY" },
  { name: "Midlothian Council", address: "Midlothian House, 40-46 Buccleuch Street, Dalkeith, EH22 1DN" },
  { name: "North Ayrshire Council", address: "Cunninghame House, Friars Croft, Irvine, KA12 8EE" },
  { name: "North Lanarkshire Council", address: "Civic Centre, Windmillhill Street, Motherwell, ML1 1AB" },
  { name: "Orkney Islands Council", address: "Council Offices, School Place, Kirkwall, KW15 1NY" },
  { name: "Perth and Kinross Council", address: "2 High Street, Perth, PH1 5PH" },
  { name: "Renfrewshire Council", address: "Renfrewshire House, Cotton Street, Paisley, PA1 1WB" },
  { name: "Scottish Borders Council", address: "Council Headquarters, Newtown St Boswells, Melrose, TD6 0SA" },
  { name: "Shetland Islands Council", address: "8 North Ness, Lerwick, Shetland, ZE1 0LZ" },
  { name: "South Ayrshire Council", address: "County Buildings, Wellington Square, Ayr, KA7 1DR" },
  { name: "South Lanarkshire Council", address: "Council Offices, Almada Street, Hamilton, ML3 0AA" },
  { name: "Stirling Council", address: "Old Viewforth, 14-20 Pitt Terrace, Stirling, FK8 2ET" },
  { name: "The Highland Council", address: "Council Headquarters, Glenurquhart Road, Inverness, IV3 5NX" },
  { name: "The Moray Council", address: "Council Office, High Street, Elgin, IV30 1BX" },
  { name: "West Dunbartonshire Council", address: "Council Offices, 16 Church Street, Dumbarton, G82 1QL" },
  { name: "West Lothian Council", address: "West Lothian Civic Centre, Howden South Road, Livingston, EH54 6FF" },
] as const;

export const ENGLAND_LOCAL_AUTHORITIES: readonly LocalAuthority[] = [
  { name: "Barking and Dagenham London Borough Council", address: "Barking Town Hall, 1 Town Square, Barking, IG11 7LU" },
  { name: "Barnet London Borough Council", address: "2 Bristol Avenue, Colindale, London, NW9 4EW" },
  { name: "Barnsley Metropolitan Borough Council", address: "Town Hall, Church Street, Barnsley, S70 2TA" },
  { name: "Bath and North East Somerset Council", address: "Guildhall, High Street, Bath, BA1 5AW" },
  { name: "Bedford Borough Council", address: "Borough Hall, Cauldwell Street, Bedford, MK42 9AP" },
  { name: "Bexley London Borough Council", address: "Civic Offices, 2 Watling Street, Bexleyheath, DA6 7AT" },
  { name: "Birmingham City Council", address: "Council House, Victoria Square, Birmingham, B1 1BB" },
  { name: "Blackburn with Darwen Borough Council", address: "Town Hall, King William Street, Blackburn, BB1 7DY" },
  { name: "Blackpool Council", address: "Number One Bickerstaffe Square, Talbot Road, Blackpool, FY1 3AH" },
  { name: "Bolton Council", address: "Town Hall, Victoria Square, Bolton, BL1 1RU" },
  { name: "Bournemouth, Christchurch and Poole Council", address: "BCP Civic Centre, Bourne Avenue, Bournemouth, BH2 6DY" },
  { name: "Bracknell Forest Council", address: "Time Square, Market Street, Bracknell, RG12 1JD" },
  { name: "Bradford Metropolitan District Council", address: "City Hall, Centenary Square, Bradford, BD1 1HY" },
  { name: "Brent London Borough Council", address: "Brent Civic Centre, Engineers Way, Wembley, HA9 0FJ" },
  { name: "Brighton and Hove City Council", address: "Hove Town Hall, Norton Road, Hove, BN3 3BQ" },
  { name: "Bristol City Council", address: "City Hall, College Green, Bristol, BS1 5TR" },
  { name: "Bromley London Borough Council", address: "Churchill Court, 2 Westmoreland Road, Bromley, BR1 1AS" },
  { name: "Buckinghamshire Council", address: "The Gateway, Gatehouse Road, Aylesbury, HP19 8FF" },
  { name: "Bury Council", address: "Town Hall, Knowsley Street, Bury, BL9 0SW" },
  { name: "Calderdale Council", address: "Town Hall, Crossley Street, Halifax, HX1 1UJ" },
  { name: "Cambridgeshire County Council", address: "New Shire Hall, Emery Crescent, Enterprise Campus, Alconbury Weald, Huntingdon, PE28 4YE" },
  { name: "Camden London Borough Council", address: "5 Pancras Square, London, N1C 4AG" },
  { name: "Central Bedfordshire Council", address: "Priory House, Monks Walk, Chicksands, Shefford, SG17 5TQ" },
  { name: "Cheshire East Council", address: "Delamere House, Delamere Street, Crewe, CW1 2LL" },
  { name: "Cheshire West and Chester Council", address: "58 Nicholas Street, Chester, CH1 2NP" },
  { name: "City of Doncaster Council", address: "Civic Office, Waterdale, Doncaster, DN1 3BU" },
  { name: "City of London Corporation", address: "Guildhall, Gresham Street, London, EC2V 7HH" },
  { name: "City of Wolverhampton Council", address: "Civic Centre, St Peter's Square, Wolverhampton, WV1 1SH" },
  { name: "City of York Council", address: "West Offices, Station Rise, York, YO1 6GA" },
  { name: "Cornwall Council", address: "New County Hall, Treyew Road, Truro, TR1 3AY" },
  { name: "Council of the Isles of Scilly", address: "Town Hall, The Parade, St Mary's, Isles of Scilly, TR21 0LW" },
  { name: "Coventry City Council", address: "Council House, Earl Street, Coventry, CV1 5RR" },
  { name: "Croydon London Borough Council", address: "Bernard Weatherill House, 8 Mint Walk, Croydon, CR0 1EA" },
  { name: "Cumberland Council", address: "Cumbria House, 117 Botchergate, Carlisle, CA1 1RD" },
  { name: "Darlington Borough Council", address: "Town Hall, Feethams, Darlington, DL1 5QT" },
  { name: "Derby City Council", address: "Council House, Corporation Street, Derby, DE1 2FS" },
  { name: "Derbyshire County Council", address: "County Hall, Matlock, DE4 3AG" },
  { name: "Devon County Council", address: "County Hall, Topsham Road, Exeter, EX2 4QD" },
  { name: "Dorset Council", address: "County Hall, Colliton Park, Dorchester, DT1 1XJ" },
  { name: "Dudley Metropolitan Borough Council", address: "The Council House, Priory Road, Dudley, DY1 1HF" },
  { name: "Durham County Council", address: "County Hall, Aykley Heads, Durham, DH1 5UL" },
  { name: "Ealing London Borough Council", address: "Perceval House, 14-16 Uxbridge Road, Ealing, London, W5 2HL" },
  { name: "East Riding of Yorkshire Council", address: "County Hall, Cross Street, Beverley, HU17 9BA" },
  { name: "East Sussex County Council", address: "County Hall, St Anne's Crescent, Lewes, BN7 1UE" },
  { name: "Enfield London Borough Council", address: "Civic Centre, Silver Street, Enfield, EN1 3XA" },
  { name: "Essex County Council", address: "County Hall, Market Road, Chelmsford, CM1 1QH" },
  { name: "Gateshead Council", address: "Civic Centre, Regent Street, Gateshead, NE8 1HH" },
  { name: "Gloucestershire County Council", address: "Shire Hall, Westgate Street, Gloucester, GL1 2TG" },
  { name: "Greenwich Royal Borough Council", address: "Woolwich Town Hall, Wellington Street, Woolwich, London, SE18 6PW" },
  { name: "Hackney London Borough Council", address: "Hackney Town Hall, Mare Street, London, E8 1EA" },
  { name: "Halton Borough Council", address: "Municipal Building, Kingsway, Widnes, WA8 7QF" },
  { name: "Hammersmith and Fulham London Borough Council", address: "Town Hall, King Street, Hammersmith, London, W6 9JU" },
  { name: "Hampshire County Council", address: "The Castle, Castle Avenue, Winchester, SO23 8UJ" },
  { name: "Haringey London Borough Council", address: "Haringey Civic Centre, 255 High Road, Wood Green, London, N22 8LE" },
  { name: "Harrow London Borough Council", address: "Forward Drive, Harrow, HA3 8NT" },
  { name: "Hartlepool Borough Council", address: "Civic Centre, Victoria Road, Hartlepool, TS24 8AY" },
  { name: "Havering London Borough Council", address: "Town Hall, Main Road, Romford, RM1 3BB" },
  { name: "Herefordshire Council", address: "Plough Lane, Hereford, HR4 0LE" },
  { name: "Hertfordshire County Council", address: "Robertson House, Six Hills Way, Stevenage, SG1 2FQ" },
  { name: "Hillingdon London Borough Council", address: "Civic Centre, High Street, Uxbridge, UB8 1UW" },
  { name: "Hounslow London Borough Council", address: "Hounslow House, 7 Bath Road, Hounslow, TW3 3EB" },
  { name: "Isle of Wight Council", address: "County Hall, High Street, Newport, PO30 1UD" },
  { name: "Islington London Borough Council", address: "Town Hall, Upper Street, London, N1 2UD" },
  { name: "Kensington and Chelsea Royal Borough Council", address: "Kensington Town Hall, Hornton Street, London, W8 7NX" },
  { name: "Kent County Council", address: "County Hall, Sandling Road, Maidstone, ME14 1XQ" },
  { name: "Kingston upon Hull City Council", address: "The Guildhall, Alfred Gelder Street, Hull, HU1 2AA" },
  { name: "Kingston upon Thames Royal Borough Council", address: "Guildhall, High Street, Kingston upon Thames, KT1 1EU" },
  { name: "Kirklees Council", address: "Civic Centre 3, Market Street, Huddersfield, HD1 2EY" },
  { name: "Knowsley Metropolitan Borough Council", address: "Municipal Buildings, Archway Road, Huyton, L36 9YU" },
  { name: "Lambeth London Borough Council", address: "Lambeth Civic Centre, 6 Brixton Hill, London, SW2 1EG" },
  { name: "Lancashire County Council", address: "County Hall, Fishergate, Preston, PR1 8XJ" },
  { name: "Leeds City Council", address: "Civic Hall, Calverley Street, Leeds, LS1 1UR" },
  { name: "Leicester City Council", address: "City Hall, 115 Charles Street, Leicester, LE1 1FZ" },
  { name: "Leicestershire County Council", address: "County Hall, Glenfield, Leicester, LE3 8RA" },
  { name: "Lewisham London Borough Council", address: "Laurence House, 1 Catford Road, London, SE6 4RU" },
  { name: "Lincolnshire County Council", address: "County Offices, Newland, Lincoln, LN1 1YL" },
  { name: "Liverpool City Council", address: "Cunard Building, Water Street, Liverpool, L3 1AH" },
  { name: "Luton Borough Council", address: "Town Hall, George Street, Luton, LU1 2BQ" },
  { name: "Manchester City Council", address: "Town Hall, Albert Square, Manchester, M2 5DB" },
  { name: "Medway Council", address: "Gun Wharf, Dock Road, Chatham, ME4 4TR" },
  { name: "Merton London Borough Council", address: "Merton Civic Centre, London Road, Morden, SM4 5DX" },
  { name: "Middlesbrough Council", address: "Town Hall, Albert Road, Middlesbrough, TS1 2QJ" },
  { name: "Milton Keynes City Council", address: "Civic Offices, 1 Saxon Gate East, Milton Keynes, MK9 3EJ" },
  { name: "Newcastle upon Tyne City Council", address: "Civic Centre, Barras Bridge, Newcastle upon Tyne, NE1 8QH" },
  { name: "Newham London Borough Council", address: "Newham Dockside, 1000 Dockside Road, London, E16 2QU" },
  { name: "Norfolk County Council", address: "County Hall, Martineau Lane, Norwich, NR1 2DH" },
  { name: "North East Lincolnshire Council", address: "Municipal Offices, Town Hall Square, Grimsby, DN31 1HU" },
  { name: "North Lincolnshire Council", address: "Civic Centre, Ashby Road, Scunthorpe, DN16 1AB" },
  { name: "North Northamptonshire Council", address: "Corby Cube, George Street, Corby, NN17 1QG" },
  { name: "North Somerset Council", address: "Town Hall, Walliscote Grove Road, Weston-super-Mare, BS23 1UJ" },
  { name: "North Tyneside Council", address: "Quadrant, The Silverlink North, Cobalt Business Park, North Tyneside, NE27 0BY" },
  { name: "North Yorkshire Council", address: "County Hall, Racecourse Lane, Northallerton, DL7 8AD" },
  { name: "Northumberland County Council", address: "County Hall, Morpeth, NE61 2EF" },
  { name: "Nottingham City Council", address: "Loxley House, Station Street, Nottingham, NG2 3NG" },
  { name: "Nottinghamshire County Council", address: "County Hall, Loughborough Road, West Bridgford, Nottingham, NG2 7QP" },
  { name: "Oldham Council", address: "Civic Centre, West Street, Oldham, OL1 1UT" },
  { name: "Oxfordshire County Council", address: "County Hall, New Road, Oxford, OX1 1ND" },
  { name: "Peterborough City Council", address: "Sand Martin House, Bittern Way, Fletton Quays, Peterborough, PE2 8TY" },
  { name: "Plymouth City Council", address: "Civic Centre, Armada Way, Plymouth, PL1 2AA" },
  { name: "Portsmouth City Council", address: "Civic Offices, Guildhall Square, Portsmouth, PO1 2AL" },
  { name: "Reading Borough Council", address: "Civic Offices, Bridge Street, Reading, RG1 2LU" },
  { name: "Redbridge London Borough Council", address: "Town Hall, 128-142 High Road, Ilford, IG1 1DD" },
  { name: "Redcar and Cleveland Borough Council", address: "Redcar and Cleveland House, Kirkleatham Street, Redcar, TS10 1RT" },
  { name: "Richmond upon Thames London Borough Council", address: "Civic Centre, 44 York Street, Twickenham, TW1 3BZ" },
  { name: "Rochdale Borough Council", address: "Number One Riverside, Smith Street, Rochdale, OL16 1XU" },
  { name: "Rotherham Metropolitan Borough Council", address: "Riverside House, Main Street, Rotherham, S60 1AE" },
  { name: "Rutland County Council", address: "Catmose, Oakham, LE15 6HP" },
  { name: "Salford City Council", address: "Salford Civic Centre, Chorley Road, Swinton, M27 5AW" },
  { name: "Sandwell Metropolitan Borough Council", address: "Sandwell Council House, Freeth Street, Oldbury, B69 3DE" },
  { name: "Sefton Council", address: "Bootle Town Hall, Oriel Road, Bootle, L20 7AE" },
  { name: "Sheffield City Council", address: "Town Hall, Pinstone Street, Sheffield, S1 2HH" },
  { name: "Shropshire Council", address: "Shirehall, Abbey Foregate, Shrewsbury, SY2 6ND" },
  { name: "Slough Borough Council", address: "Observatory House, 25 Windsor Road, Slough, SL1 2EL" },
  { name: "Solihull Metropolitan Borough Council", address: "Council House, Manor Square, Solihull, B91 3QB" },
  { name: "Somerset Council", address: "County Hall, The Crescent, Taunton, TA1 4DY" },
  { name: "South Gloucestershire Council", address: "Council Offices, Badminton Road, Yate, Bristol, BS37 5AF" },
  { name: "South Tyneside Council", address: "Town Hall, Westoe Road, South Shields, NE33 2RL" },
  { name: "Southampton City Council", address: "Civic Centre, Civic Centre Road, Southampton, SO14 7LY" },
  { name: "Southend-on-Sea City Council", address: "Civic Centre, Victoria Avenue, Southend-on-Sea, SS2 6ER" },
  { name: "Southwark London Borough Council", address: "160 Tooley Street, London, SE1 2QH" },
  { name: "St Helens Borough Council", address: "Town Hall, Victoria Square, St Helens, WA10 1HP" },
  { name: "Staffordshire County Council", address: "County Buildings, Martin Street, Stafford, ST16 2LH" },
  { name: "Stockport Metropolitan Borough Council", address: "Town Hall, Edward Street, Stockport, SK1 3XE" },
  { name: "Stockton-on-Tees Borough Council", address: "Municipal Buildings, Church Road, Stockton-on-Tees, TS18 1LD" },
  { name: "Stoke-on-Trent City Council", address: "Civic Centre, Glebe Street, Stoke-on-Trent, ST4 1HH" },
  { name: "Suffolk County Council", address: "Endeavour House, 8 Russell Road, Ipswich, IP1 2BX" },
  { name: "Sunderland City Council", address: "City Hall, Plater Way, Sunderland, SR1 3AA" },
  { name: "Surrey County Council", address: "Woodhatch Place, 11 Cockshot Hill, Reigate, RH2 8EF" },
  { name: "Sutton London Borough Council", address: "Civic Offices, St Nicholas Way, Sutton, SM1 1EA" },
  { name: "Swindon Borough Council", address: "Civic Offices, Euclid Street, Swindon, SN1 2JH" },
  { name: "Tameside Metropolitan Borough Council", address: "Tameside One, Market Place, Ashton-under-Lyne, OL6 6BH" },
  { name: "Telford and Wrekin Council", address: "Addenbrooke House, Ironmasters Way, Telford, TF3 4NT" },
  { name: "Thurrock Council", address: "Civic Offices, New Road, Grays, RM17 6SL" },
  { name: "Torbay Council", address: "Town Hall, Castle Circus, Torquay, TQ1 3DR" },
  { name: "Tower Hamlets London Borough Council", address: "Town Hall, 160 Whitechapel Road, London, E1 1BJ" },
  { name: "Trafford Council", address: "Trafford Town Hall, Talbot Road, Stretford, M32 0TH" },
  { name: "Wakefield Council", address: "Town Hall, Wood Street, Wakefield, WF1 2HQ" },
  { name: "Walsall Council", address: "Civic Centre, Darwall Street, Walsall, WS1 1TP" },
  { name: "Waltham Forest London Borough Council", address: "Waltham Forest Town Hall, Forest Road, London, E17 4JF" },
  { name: "Wandsworth London Borough Council", address: "The Town Hall, Wandsworth High Street, London, SW18 2PU" },
  { name: "Warrington Borough Council", address: "New Town House, Buttermarket Street, Warrington, WA1 2NH" },
  { name: "Warwickshire County Council", address: "Shire Hall, Northgate Street, Warwick, CV34 4RL" },
  { name: "West Berkshire Council", address: "Council Offices, Market Street, Newbury, RG14 5LD" },
  { name: "West Northamptonshire Council", address: "One Angel Square, Angel Street, Northampton, NN1 1ED" },
  { name: "West Sussex County Council", address: "County Hall, West Street, Chichester, PO19 1RQ" },
  { name: "Westminster City Council", address: "Westminster City Hall, 64 Victoria Street, London, SW1E 6QP" },
  { name: "Westmorland and Furness Council", address: "South Lakeland House, Lowther Street, Kendal, LA9 4DQ" },
  { name: "Wigan Council", address: "Town Hall, Library Street, Wigan, WN1 1YN" },
  { name: "Wiltshire Council", address: "County Hall, Bythesea Road, Trowbridge, BA14 8JN" },
  { name: "Windsor and Maidenhead Royal Borough Council", address: "Town Hall, St Ives Road, Maidenhead, SL6 1RF" },
  { name: "Wirral Metropolitan Borough Council", address: "Wallasey Town Hall, Brighton Street, Wallasey, CH44 8ED" },
  { name: "Wokingham Borough Council", address: "Civic Offices, Shute End, Wokingham, RG40 1BN" },
  { name: "Worcestershire County Council", address: "County Hall, Spetchley Road, Worcester, WR5 2NP" },
] as const;

export function localAuthoritiesFor(
  jurisdiction: "Scotland" | "England",
): readonly LocalAuthority[] {
  return jurisdiction === "Scotland"
    ? SCOTLAND_LOCAL_AUTHORITIES
    : ENGLAND_LOCAL_AUTHORITIES;
}
