import type { Intake } from "./schema";

// Fires when a logged-in user *other than* Colin generates a DSA whose
// MCR signing block carries Sharon + Colin's stored signatures. The
// intent is a tattle email to Colin so unexpected signed copies get
// noticed quickly.
//
// Implementation: a single POST to the Resend HTTP API. Resend is used
// here over the SDK to avoid a new dependency for ~10 lines of work.

const OWNER_EMAIL = "colin.adam@mcrpathways.org";

export interface NotifyDeps {
  fetch: typeof fetch;
  now: () => Date;
}

export interface NotifyArgs {
  userEmail: string | undefined;
  intake: Intake;
}

export async function notifySignedGeneration(
  args: NotifyArgs,
  deps: NotifyDeps = { fetch, now: () => new Date() },
): Promise<void> {
  // Local dev uses a mocked user (see src/lib/supabase/server.ts).
  // Skip outright so dev runs don't spam Colin.
  if (process.env.NODE_ENV !== "production") return;

  if (!args.userEmail || args.userEmail === OWNER_EMAIL) return;

  const apiKey = process.env.RESEND_API_KEY;
  if (!apiKey) {
    // Missing key shouldn't break DSA generation — log and move on.
    // The action's main effect (the doc download) is more important than
    // the tattle.
    console.warn(
      "RESEND_API_KEY not set; skipping signed-DSA notification email",
    );
    return;
  }

  const { counterparty, jurisdiction } = args.intake;
  const subject = `Signed DSA generated by ${args.userEmail}`;
  const body = [
    `User: ${args.userEmail}`,
    `Counterparty: ${counterparty.shortName} — ${counterparty.legalName}`,
    `Jurisdiction: ${jurisdiction}`,
    `Generated at: ${deps.now().toISOString()}`,
    "",
    "The DSA Builder rendered Sharon's and Colin's signatures into the",
    "downloaded document. If this user was not authorised to issue a",
    "signed copy, follow up with them.",
  ].join("\n");

  // 4-second timeout — Resend is normally well under 500ms, so 4s leaves
  // generous headroom while ensuring a stuck request can't pin the
  // Vercel function container open indefinitely.
  let res: Response;
  try {
    res = await deps.fetch("https://api.resend.com/emails", {
      method: "POST",
      headers: {
        Authorization: `Bearer ${apiKey}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        from: "DSA Builder <onboarding@resend.dev>",
        to: OWNER_EMAIL,
        subject,
        text: body,
      }),
      signal: AbortSignal.timeout(4000),
    });
  } catch (err) {
    console.warn("Resend POST failed (network or timeout):", err);
    return;
  }

  if (!res.ok) {
    const text = await res.text().catch(() => "(no body)");
    console.warn(
      `Resend rejected signed-DSA notification: ${res.status} ${text}`,
    );
  }
}
